
# generated by jobsub_lite
# 
universe           = vanilla
executable         = simple.sh
arguments          = --nfile 1  --group uboone  -g  -c wrapper.fcl  --ups uboonecode  -r v08_00_00_51  -b e17:prof  --localtar /pnfs/uboone/resilient/users/taniuchi/KaonProduction/tarballs/Kaon_v08_00_00_51.tar  --workdir /pnfs/uboone/scratch/users/taniuchi/v08_00_00_51/make_kaon_events_numi_fhc_run1_assok_overlay_deftest2/full_overlay/gen/workdir  --outdir /pnfs/uboone/scratch/users/taniuchi/v08_00_00_51/make_kaon_events_numi_fhc_run1_assok_overlay_deftest2/full_overlay/gen/outdir  --logdir /pnfs/uboone/scratch/users/taniuchi/v08_00_00_51/make_kaon_events_numi_fhc_run1_assok_overlay_deftest2/full_overlay/gen/logdir  --os SL7  -n 2000  --njobs 10 --data_file_type root  --output make_kaon_events_numi_fhc_run1_assok_overlay_deftest2_${PROCESS}_%tc_g4.root  --init /cvmfs/uboone.opensciencegrid.org/products/setup_uboone.sh  --validate  --declare  --copy

output             = gen-make_kaon_events_numi_fhc_run1_assok_overlay_deftest2-v08_00_00_51.sh2023_06_19_0914000c7d2d0b-cafc-4bb1-b0cc-267465898d9bcluster.$(Cluster).$(Process).out
error              = gen-make_kaon_events_numi_fhc_run1_assok_overlay_deftest2-v08_00_00_51.sh2023_06_19_0914000c7d2d0b-cafc-4bb1-b0cc-267465898d9bcluster.$(Cluster).$(Process).err
log                = gen-make_kaon_events_numi_fhc_run1_assok_overlay_deftest2-v08_00_00_51.sh2023_06_19_0914000c7d2d0b-cafc-4bb1-b0cc-267465898d9bcluster.$(Cluster).$(Process).log


JOBSUBJOBSECTION=$(Process)


environment        = CM1=$(CM1);CM2=$(CM2);CLUSTER=$(Cluster);PROCESS=$(Process);JOBSUBJOBSECTION=$(JOBSUBJOBSECTION);CONDOR_TMP=/nashome/t/taniuchi/.cache/jobsub_lite/js_2023_06_19_091400_0c7d2d0b-cafc-4bb1-b0cc-267465898d9b;BEARER_TOKEN_FILE=.condor_creds/uboone_dd28b7e9c2.use;CONDOR_EXEC=/tmp;DAGMANJOBID=$(DAGManJobId);GRID_USER=taniuchi;JOBSUBJOBID=$(CLUSTER).$(PROCESS)@jobsub05.fnal.gov;EXPERIMENT=uboone;
rank               = Mips / 2 + Memory
job_lease_duration = 3600
transfer_output    = True
transfer_error     = True
transfer_executable= True
transfer_input_files = gen-make_kaon_events_numi_fhc_run1_assok_overlay_deftest2-v08_00_00_51.sh
# if transfer_output_files is not explicitly set, condor will transfer ALL the files the job touches (unless in grid universe)
transfer_output_files = .empty_file
when_to_transfer_output = ON_EXIT_OR_EVICT

request_memory = 2000.0
request_disk = 20971520.0KB

+JobsubClientDN="/DC=org/DC=cilogon/C=US/O=Fermi National Accelerator Laboratory/OU=People/CN=Natsumi Taniuchi/CN=UID:taniuchi/CN=3091388192"
+JobsubClientIpAddress="131.225.67.95"
+JobsubServerVersion="jobsub_lite-v1.3.4"
+JobsubClientVersion="jobsub_lite-v1.3.4"
+JobsubClientKerberosPrincipal="taniuchi@FNAL.GOV"
+JOB_EXPECTED_MAX_LIFETIME = 86400.0
notify_user = "taniuchi@fnal.gov"
notification = Never

# set command to user executable for jobsub_q
+JobsubCmd = "gen-make_kaon_events_numi_fhc_run1_assok_overlay_deftest2-v08_00_00_51.sh"


+AccountingGroup = "group_uboone.taniuchi"


+Jobsub_Group="uboone"
+JobsubJobId="$(CLUSTER).$(PROCESS)@jobsub05.fnal.gov"
+JobsubOutputURL="https://fndcadoor.fnal.gov:2880/fermigrid/jobsub/jobs/2023_06_19/0c7d2d0b-cafc-4bb1-b0cc-267465898d9b"
+JobsubUUID="0c7d2d0b-cafc-4bb1-b0cc-267465898d9b"
+Drain = False
# default for remote submits is to keep completed jobs in the queue for 10 days
+LeaveJobInQueue = False


+DESIRED_SITES = ""


+GeneratedBy ="jobsub_lite-v1.3.4 jobsub05.fnal.gov"



+DESIRED_usage_model="DEDICATED,OPPORTUNISTIC,OFFSITE"


requirements  = target.machine =!= MachineAttrMachine1 && target.machine =!= MachineAttrMachine2 && (isUndefined(DesiredOS) || stringListsIntersect(toUpper(DesiredOS),IFOS_installed)) && (stringListsIntersect(toUpper(target.HAS_usage_model), toUpper(my.DESIRED_usage_model))) && (TARGET.HAS_SINGULARITY=?=true)



+SingularityImage="/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:latest"


#
# this is supposed to get us output even if jobs are held(?)
#
+SpoolOnEvict = false
#
#
#

# Credentials

use_oauth_services = uboone

uboone_oauth_permissions_dd28b7e9c2 = " compute.read compute.create compute.cancel compute.modify storage.read:/uboone storage.create:/fermigrid/jobsub/jobs storage.read:/uboone/resilient/jobsub_stage storage.create:/uboone/resilient/jobsub_stage storage.create:/uboone/scratch/users/taniuchi storage.create:/uboone/persistent/users/taniuchi "




+x509userproxy = "/tmp/x509up_u58504"

delegate_job_GSI_credentials_lifetime = 0


queue 10